name: stac
description: Stac is a Server-Driven UI (SDUI) framework for Flutter. Stac allows you to build beautiful cross-platform applications with JSON in real time.
version: 1.0.0-dev.4
homepage: https://github.com/StacDev/stac

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

topics:
  - ui
  - widget
  - server-driven-ui
  - dynamic-widgets

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  dio: ^5.8.0+1
  stac_framework: ^0.3.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  stac_logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5