name: stac_framework
description: The Stac Framework package provides a straightforward way to create custom parsers for widgets and actions in Stac. It is useful for extending Stac's functionality or implementing custom widgets and actions.
version: 0.1.0
homepage: https://github.com/stac/stac

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
