name: mirai_webview
description: A WebView Parser for Mirai. A wrapper of `webview_flutter` package for Mirai.
version: 0.1.0
homepage: https://github.com/buildMirai/mirai

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  mirai_framework: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0

